# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SharePastExam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SharePastExam
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'PKHUD', '~> 5.0'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Nuke'
  pod 'SDWebImageSwiftUI'
  pod 'Kingfisher'
  pod 'SkeletonView'
end
